name: Deployment
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Set up Node
        uses: actions/setup-node@master
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install
        
      - name: Setting .env
        run: |
          echo "REACT_APP_OPENAI_API_KEY=${{ secrets.REACT_APP_OPENAI_API_KEY }}" >> .env
          echo "REACT_APP_APIKEY=${{ secrets.REACT_APP_APIKEY }}" >> .env
          echo "REACT_APP_AUTH_DOMAIN=${{ secrets.REACT_APP_AUTH_DOMAIN }}" >> .env
          echo "REACT_APP_PROJECT_ID=${{ secrets.REACT_APP_PROJECT_ID }}" >> .env
          echo "REACT_APP_STORAGE_BUCKET=${{ secrets.REACT_APP_STORAGE_BUCKET }}" >> .env
          echo "REACT_APP_MESSAGIN_ID=${{ secrets.REACT_APP_MESSAGIN_ID }}" >> .env
          echo "REACT_APP_APP_ID=${{ secrets.REACT_APP_APP_ID }}" >> .env
          echo "REACT_APP_MEASUREMENT_ID=${{ secrets.REACT_APP_MEASUREMENT_ID }}" >> .env

      - name: Build
        run: npm run build
        env:
          CI: false
          NODE_ENV: production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
